correctcomputation/checkedc-clang

clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/ProgramInfo.h
clang/include/clang/CConv/RewriteUtils.h
clang/include/clang/CConv/Utils.h
clang/lib/CConv/ArrayBoundsInferenceConsumer.cpp
clang/lib/CConv/CConv.cpp
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/GatherTool.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/lib/CConv/Utils.cpp

Now each function has a single set of constraints, not two.

Removed Def/Decl constraint distinction

---

clang/include/clang/CConv/ProgramInfo.h
clang/lib/CConv/ProgramInfo.cpp
clang/test/CheckedCRewriter/extGVar.c
clang/test/CheckedCRewriter/extGVarbar1.c
clang/test/CheckedCRewriter/extGVarbar2.c
clang/test/CheckedCRewriter/extGVarm1.c
clang/test/CheckedCRewriter/extGVarm2.c
clang/test/CheckedCRewriter/extGVarm3.c

Fixed #73 and added three (passing) tests (1 normal, 2 multifile).

Fixed issue 73

---

clang/lib/CConv/ConstraintResolver.cpp
clang/test/CheckedCRewriter/addrof_crash.c
clang/test/CheckedCRewriter/amper.c
clang/test/CheckedCRewriter/ptrptr.c
clang/test/CheckedCRewriter/simple_locals.c

Fix things up a bit so that assertion isn't violated anymore.

Addr of crash fix

---

clang/include/clang/CConv/ConstraintVariables.h
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/test/CheckedCRewriter/3d-allocation.c
clang/test/CheckedCRewriter/basic.c
clang/test/CheckedCRewriter/graphs.c
clang/test/CheckedCRewriter/graphs2.c
clang/test/CheckedCRewriter/linkedlist.c

Also changed some tests to add back standard headers. Fixes issues #84 #101 and #102

New change for iss84

---

clang/include/clang/CConv/ConstraintsGraph.h
clang/lib/CConv/Constraints.cpp
clang/lib/CConv/ConstraintsGraph.cpp

Address #121. Constraint graphs are kept separate while solving again.

 Adjust constraint graph rep

---

clang/lib/CConv/Utils.cpp
clang/test/CheckedCRewriter/unsigned_signed_cast.c

This PR solves issue #164 
It handles conversions between unsigned integers and chars. (C does not support unsigned floats). Also added one passing test.

Fix for issue 164

---

clang-tools-extra/clangd/CConvertDiagnostics.cpp
clang-tools-extra/clangd/CConvertDiagnostics.h
clang-tools-extra/clangd/ClangdServer.cpp
clang-tools-extra/clangd/ClangdServer.h
clang/include/clang/CConv/CConv.h
clang/include/clang/CConv/CConvInteractiveData.h
clang/include/clang/CConv/Constraints.h
clang/include/clang/CConv/ConstraintsGraph.h
clang/include/clang/CConv/ProgramInfo.h
clang/lib/CConv/CConv.cpp
clang/lib/CConv/CConvInteractiveData.cpp
clang/lib/CConv/Constraints.cpp
clang/lib/CConv/ConstraintsGraph.cpp
clang/lib/CConv/ProgramInfo.cpp

Refactoring and changes to ensure the current version of tool works with clangd

Changes to integrate with clangd

---

clang/include/clang/CConv/ArrayBoundsInferenceConsumer.h
clang/lib/CConv/ArrayBoundsInferenceConsumer.cpp
clang/test/CheckedCRewriter/arrboundsheuristics.c

Fixing issues faced while evaluating benchmarks.

Fixing issue https://github.com/plum-umd/checkedc-clang/issues/206

---

clang/include/clang/CConv/TypeVariableAnalysis.h
clang/include/clang/CConv/Utils.h
clang/lib/CConv/TypeVariableAnalysis.cpp
clang/lib/CConv/Utils.cpp
clang/test/CheckedCRewriter/type_params.c

Fix for #209 I think. Merge it works, let me know if it doesn't.

Let type parameters be instantiated by array types 

---

clang/include/clang/CConv/DeclRewriter.h
clang/include/clang/CConv/RewriteUtils.h
clang/lib/CConv/DeclRewriter.cpp

The build now works without RTTI enabled.

Use llvm rtti for DeclReplacement class

---

clang/include/clang/CConv/CheckedRegions.h
clang/lib/CConv/CheckedRegions.cpp
clang/test/CheckedCRewriter/alreadychecked.c

Checked Region respects manually added annotations

---

clang/include/clang/CConv/CCGlobalOptions.h
clang/include/clang/CConv/CConv.h
clang/include/clang/CConv/DeclRewriter.h
clang/include/clang/CConv/RewriteUtils.h
clang/lib/CConv/CConv.cpp
clang/lib/CConv/CMakeLists.txt
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/DeclRewriter.cpp
clang/tools/cconv-standalone/CConvStandalone.cpp
clang/tools/cconv-standalone/CMakeLists.txt

3C applicable refactoring for new 5C itype removal pull request.

Itype refactor 3C

---

clang-tools-extra/clangd/CConvertDiagnostics.cpp
clang-tools-extra/clangd/ClangdServer.cpp
clang-tools-extra/clangd/tool/ClangdMain.cpp
clang/include/clang/CConv/CConv.h
clang/include/clang/CConv/CConvInteractiveData.h
clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/Constraints.h
clang/include/clang/CConv/PersistentSourceLoc.h
clang/include/clang/CConv/ProgramInfo.h
clang/include/clang/CConv/RewriteUtils.h
clang/lib/CConv/CConv.cpp
clang/lib/CConv/CConvInteractiveData.cpp
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/Constraints.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/b30_structprotocastimplicitunsafeuseunsafe.c
clang/test/CheckedCRewriter/root_cause.c
clang/tools/cconv-standalone/CConvStandalone.cpp

1. General improvement to root cause of wildness diagnostics.
1. Reason strings added to causes of wildness where they were missing
2. Improved accuracy of root cause source location
3. Tests for root cause diagnostics  
2. Pointer level root cause information
1. By considering pointers instead of atoms, the root cause analysis can  detect when different causes of wildness affect the same variable at different levels of indirection.

Root cause of wildness improvements

---

clang/include/clang/3C/AVarGraph.h
clang/lib/3C/AVarGraph.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/Constraints.cpp
clang/lib/3C/MappingVisitor.cpp
clang/lib/3C/RewriteUtils.cpp
clang/lib/3C/Utils.cpp

Note: This change has been approved in principle, and Mike said code-maintenance changes that have been approved in principle don't need to be reviewed by anyone else before merging.  I'm filing a pull request for record-keeping purposes and because I need to merge the branch via a merge commit anyway since the first commit on the branch doesn't compile.
The regression tests passed.

Fix header dependencies

---

clang/lib/3C/StructInit.cpp
clang/test/3C/qualifiers.c

Add extern and static qualifiers to initialized variables

---

clang/include/clang/3C/ConstraintsGraph.h

Fixes the performance issues in graph construction found in PR #356 
The graph base class provided by LLVM does a linear time membership check when inserting a node into a graph. This change avoids that check by maintaining a set of nodes that exist in graph, and using that determine if a node being inserted already exists.

Optimize node insertion method for graph class

---

clang/lib/3C/ConstraintResolver.cpp

Adds an edge `PTR -> x` for expressions `&x`. Previously, only the result
of the addrof expression had this constraint, but CheckedC prohibits
taking the address of pointers with bounds. It is possible to take the
address of an `_Array_ptr` when the pointer doesn't have bounds declared.
With this constraint added however, 3C will not let this happen.

Constrain target of addrof operator to PTR

---

clang/include/clang/3C/ConstraintsGraph.h
clang/lib/3C/AVarBoundsInfo.cpp
clang/lib/3C/ConstraintResolver.cpp
clang/test/3C/multiconstant_bounds.c

Fixing issue: https://github.com/correctcomputation/checkedc-clang/issues/390

Fixing issue: https://github.com/correctcomputation/checkedc-clang/issues/390

---

clang/include/clang/3C/ConstraintVariables.h
clang/include/clang/3C/Constraints.h
clang/include/clang/3C/ConstraintsGraph.h
clang/include/clang/3C/ProgramInfo.h
clang/include/clang/3C/Utils.h
clang/lib/3C/ConstraintBuilder.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/Constraints.cpp
clang/lib/3C/ConstraintsGraph.cpp
clang/lib/3C/ProgramInfo.cpp
clang/lib/3C/Utils.cpp
clang/test/3C/cant_be_nt.c

Solving issue of un-nullable types solving to Nt_array

---

clang/include/clang/3C/ProgramVar.h
clang/lib/3C/AVarBoundsInfo.cpp
clang/lib/3C/ProgramVar.cpp
clang/test/3C/arrboundsheuristicsglobal.c

Adding visible variables to be considered as potential bounds (with priority given to same scope variables).

Considering in scope variables as potential bounds.

---

README.md
clang/docs/checkedc/3C/INSTALL.md

This is my counterproposal to #607, attempting to address the same problems that #607 sought out to address.  Ideally, I'd like to get it into our imminent omnibus PR to Microsoft.
@mwhicks1 Can you provide an additional opinion on whether you think Microsoft will be OK with this change to the root readme (or maybe even ask them now)?  Or I guess we can just include it and revert it later if they ask during review of the omnibus PR.

Minor documentation updates (Matt's version)

---

clang/include/clang/3C/Constraints.h
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/Constraints.cpp
clang/lib/3C/ProgramInfo.cpp

The constraints we created with implications can easily be encoded with Geq constraints instead. Doing this lets us simplify the solving algorithm by removing the outer loop for firing implication constraints. This should also makes the constraint graph more easily interpreted because the relationship between the atoms of a pointer is shown explicitly by checked type edges between those atoms.

Remove implication constraints

---

clang/include/clang/3C/CastPlacement.h
clang/lib/3C/CastPlacement.cpp
clang/test/3C/cast.c

cast uses local type vars for generics

---

clang/include/clang/3C/ConstraintVariables.h
clang/include/clang/3C/TypeVariableAnalysis.h
clang/lib/3C/TypeVariableAnalysis.cpp
clang/test/3C/base_subdir/generictest.c
clang/test/3C/hasgeneric.c

Fixes https://github.com/correctcomputation/checkedc-clang/issues/668

Don't insert generic instantiations in non-writable files
