correctcomputation/checkedc-clang

clang/lib/CConv/ConstraintVariables.cpp
clang/test/CheckedCRewriter/fp.c

Returned FP was being confused with enclosing function's decl.

Fixed issue #75. 

---

clang/lib/CConv/ConstraintBuilder.cpp
clang/test/CheckedCRewriter/fp_arith.c

Implement fix for issue #74
When adding constraints for pointer arithmetic, first check that the
pointer in question is not a function pointer. If it is a function pointer, then constrain it to be WILD; otherwise proceed as before. 
Add test to validate this behavior.

Implement fix for issue #74

---

clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/test/CheckedCRewriter/ptr_array.c

Fix issue #60 .
Implement handling for array initializers by (1) collecting all constraint variables generated by all elements of the initializer into the set returned by `getExprConstraintVars`, and (2) and removing the
first pointer level when adding constraints for array initializers in `constrainConsVarGeq`.
This doesn't fully implement everything needed for `InitListExpr` since I haven't done anything about structures yet.

Array initializer

---

clang/lib/CConv/ConstraintBuilder.cpp
clang/test/CheckedCRewriter/fn_sets.c

Fix for #86. First by processing call expressions where the callee is complex expression (i.e., not a simple function or function pointer) and then by enforcing equality between function constraint variables to handle the case where the constraint vars set for this expression contains more the one element.

Function sets

---

clang/include/clang/CConv/ConstraintResolver.h
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/RewriteUtils.cpp

Gone: `LHSConstraints` and `LhsType` in `getExprConstraintVars`. The former was never necessary because we were making a copy of each return when calling a function. The latter was used in checking casts, but the prior `RvalCons`-removal commit made it redundant by leveraging `ImplicitCast` operators. `LhsType` was also used for list initializers, but that code checking it could be moved into the caller. Much cleaner!

Get expr constraint vars refactor lhs

---

clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/test/CheckedCRewriter/struct_init_list.c

Implements `getExprConstraintVars` for structure initialization lists, fixing issue #105. Structure initialization lists are treated as a series of variable assignments to each of the record fields.
This pull requests also improves the handling of array initialization lists. The `derefLHS` parameter has been removed from the `constrainConsVarGeq`, and array initialization is instead treated analogously to AddrOf using the `addAtom` method.

Structure initialization lists 

---

clang/lib/CConv/ConstraintResolver.cpp
clang/test/CheckedCRewriter/basic_checks.c
clang/test/CheckedCRewriter/refarrsubscript.c
clang/test/CheckedCRewriter/refarrsubscriptstruct.c

Fixed issue 106 and added two (passing) tests. Also modified the checked annotations in `basic_checks.c` in order to account for the fix. All conversions result in files that compile with checked-c's clang.

Fix for issue 106

---

clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/Constraints.h
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/itypecast.c

is fix addresses assignment of arguments to itype parameters.
For itype parameters, the requirement is that if the argument is checked type, then it has to match the exact type specified inside itype annotation.
For example:
void foo(int **p:itype(_Ptr<_Ptr<int>>));
void bar() {
_Ptr<_Ptr<int>> itype_match = 0;
int **wild_match;
_Ptr<int *> mis_match = 0;
// This is Okay, as this matches the itype perfectly.
foo(itype_match);
// This is Okay, as this matches the wild type.
foo(wild_match);
// This is Not Okay, because the type does not match the WILD type or itype.
foo(mis_match);
}
This fix, checks if the itype match is correct, if not, adds a cast to the argument.
I have also cleaned up code a bit to remove certain unused variables.
**With this fix, Complete automated conversion of …

Handling itype params latest

---

clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/ConstraintsGraph.h
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/Constraints.cpp
clang/lib/CConv/ConstraintsGraph.cpp

Some minor improvements to the visualization of constraint graphs:
* Combine ptyp and checked graphs into a single image with shared nodes (edges color coded to show constraint type: red -> checked constraint; blue -> ptyp constraint).
* Output a graph after implication constraints are resolved
* More meaningful names for atoms in some cases

GraphViz Improvements

---

clang/lib/CConv/RewriteUtils.cpp

Consider:
```
void foo(int *p: itype(_Ptr<int>)) {
*p = 1;
}
void bar(void) {
int *x = (int *)5;
foo(x);
}
```
Get's rewritten into:
```
void foo(int *p : itype(int*p)) {
*p = 1;
}
void bar(void) {
int *x = (int *)5;
foo(x);
}
```
Causing a syntax error at `itype(int*p)`

Fixing issue: https://github.com/plum-umd/checkedc-clang/issues/124

---

clang/include/clang/CConv/ConstraintsGraph.h
clang/lib/CConv/ConstraintsGraph.cpp

Takes care of two comments under #121: 
1.  no longer gathers set of all edges when merging graph
2. combines edges of same type going in opposite directions between a pair of nodes into a bidirectional edge.

GraphViz improvement

---

clang/lib/CConv/RewriteUtils.cpp

Removes the incorrectly placed bounds expression on strings literals seen in #143. This doesn't do anything with the constraints on strings literals, and I'm not sure exactly what we we want to  do there.

Don't output bounds expr when not array type

---

clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/Utils.cpp
clang/test/CheckedCRewriter/canonical_type_cast.c

The fix for issue #58 turned out to be fairly straightforward. `CastCheck` did not account for decayed types created by casting arrays to pointer. This also fixes explicit casts of functions to function pointer for the same reason.
The one tricky point is that
```c
void g(int p[]) {
int *x = (int *)p;
}
```
must  rewrite to 
```c
void g(_Ptr<int> p) {
_Ptr<int> x =  (int *)p;
}
```
Note that the `p` went from `int[]` to `_Ptr<int>`. This requires making the constraint from `p` to `ARR` a lower bound instead of an upper bound, but this can't be done for all arrays. For instance, `int a[1] = {1}` to `_Ptr<int> a = {1}`, is not allowed. To get around this, a check is added to determine if the array is an incomplete array type. The lower bound is used only in this case.
Another point is that …

FIx Issue #58

---

clang/include/clang/CConv/Constraints.h
clang/lib/CConv/Constraints.cpp
clang/test/CheckedCRewriter/refarrsubscript.c
clang/test/CheckedCRewriter/return_not_least.c

Changes to constraint graph solving so that the least solution is not always used for return values. The least solution is only used when the return variable has an explicit lower bound. When there is no explicit lower bound, there are two possible cases:
1. There is local variable with an upper bound that can define a lower bound for the return variable. In this case, the bounding variable is fixed (like a parameter variable) while computing the least solution.
2. There is no viable lower bound. In this case, the least solution is computed as normal, but the unbounded return variable is reset to `Ptr` and included in the final greatest solution. 
Example 1: The return value has no lower bound, so the greatest solution is used. This gives `_Ptr` rather than `_Nt_array_ptr`
```c
int *bar() …
```

Solver changes

---

clang/lib/CConv/ConstraintResolver.cpp

It looks like the problem came from union types which are something we aren't really handling at the moment. One conditionals was checking `isStructType` when it should have been catching any record types. This change just fixes that so that the union doesn't make it to the `InitListExpr` block.

Fix Issue #148

---

clang/lib/CConv/ConstraintBuilder.cpp
clang/test/CheckedCRewriter/inlinestruct_difflocs.c

Fix for #152. (with one passing test) 
Similar to the inline struct erasure problem ( issue #31 )The way we solved inline structs before was to detect if the beginning locations were exact, but the example from #152 demonstrates that sometimes struct definitions are subsumed in `VarDecl`s. (e.g. struct definition may occur from locations `9-90` while the `VarDecl` occurs from `2-93`, so their locations aren't identical, and yet the `VarDecl` shadows the struct definition). We just need to alter the way we were checking before to instead be a range of values. The caveat here, as before, is that we sacrifice conversion of the variable in exchange for conversion of the struct fields, so unlike the clean suggested conversion from #152 , the resulting conversion is: 
```
int …
```

Fix for iss152

---

clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ProgramInfo.h
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/fptrarrstructboth.c
clang/test/CheckedCRewriter/fptrarrstructbothmulti1.c
clang/test/CheckedCRewriter/fptrarrstructcallee.c
clang/test/CheckedCRewriter/fptrarrstructcalleemulti1.c
clang/test/CheckedCRewriter/fptrarrstructcaller.c
clang/test/CheckedCRewriter/fptrarrstructcallermulti1.c
clang/test/CheckedCRewriter/fptrarrstructprotoboth.c
clang/test/CheckedCRewriter/fptrarrstructprotocallee.c
clang/test/CheckedCRewriter/fptrarrstructprotocaller.c
clang/test/CheckedCRewriter/fptrarrstructprotosafe.c
clang/test/CheckedCRewriter/fptrarrstructsafe.c
clang/test/CheckedCRewriter/fptrarrstructsafemulti1.c
clang/test/CheckedCRewriter/no_casts.c

Unneeded casts were being inserted on function calls where the both the parameter and argument were `WILD` (#134). The cause of this was that the cast insertion visitor was not using the solved types for arguments. Since the initial type for all variables is `PTR`, arguments were always treated as checked variables so a cast was inserted. This PR fixes that by storing constraint variables constructed during `getExprConstraintVar` in the `Variables` map in `ProgramInfo`.
In addition to the string literal case demonstrated in the referenced issue, this fix applies to function calls, address-of operations, and compound literals. All of the following used to insert casts, but are now not rewritten.
```c
void foo(char *a);
void bar(int *a);
void baz(int a[1]);
int *wild();
void test() { …
```

Remove unneeded casts

---

clang/include/clang/CConv/ConstraintVariables.h
clang/lib/CConv/ConstraintVariables.cpp
clang/test/CheckedCRewriter/qualifiers.c

Fix for #162 by preserving these qualifiers in the same way that `const` is preserved.

Add support for volatile and restrict qualifiers 

---

clang/include/clang/CConv/AVarBoundsInfo.h
clang/include/clang/CConv/ArrayBoundsInferenceConsumer.h
clang/lib/CConv/AVarBoundsInfo.cpp
clang/lib/CConv/ArrayBoundsInferenceConsumer.cpp
clang/lib/CConv/CMakeLists.txt
clang/lib/CConv/ConstraintBuilder.cpp
clang/test/CheckedCRewriter/arrboundsadvanced.c
clang/test/CheckedCRewriter/fptrarrstructbothmulti2.c
clang/test/CheckedCRewriter/fptrarrstructcalleemulti2.c
clang/test/CheckedCRewriter/fptrarrstructcallermulti2.c
clang/test/CheckedCRewriter/fptrarrstructsafemulti2.c

This pull requests add the following feature to array bounds inference mechansim:
Consider the following example:
```
int foo(int *a, int *b, unsigned l) {
unsigned i = 0;
for (i=0; i<l; i++) {
a[i] = b[i];
}
}
```
From the above code, it is obvious that the length of `a` and `b` should be `l`. 
Consider the following a bit more complex example:
```
struct f {
int *a;
unsigned l;
};
void clear(struct f *b, int idx) {
unsigned n = b->l;
if (idx >= n) {
return;
}
b->a[idx] = 0;
}
```
Here, we can see that the length of the `f`'s struct member `a` is `l`. 
We can capture these facts by using control dependencies. Specifically, for each array indexing operation, i.e., `arr[i]`, we find all the statements that the indexing statement is **control dependent on**. 
Then, for each of the control …

Advanced array inference based on control dependencies

---

clang/lib/CConv/ConstraintBuilder.cpp
clang/test/CheckedCRewriter/type_params.c

This pull requests adds code support having checked pointers in the arguments for generic functions fixing issue #153.
When generating constraints for function call expression, this checks if the function being called has a generic interface. If it does, a map is created taking each type parameter to the set of types that are used to instantiate that parameter. The set of types for each parameter is examined, and it if all elements of the set are compatible, then the type parameter can be instantiated. This mean that we can remove the cast to `void *` around the arguments, allowing `getExprConstraintVars` to find non-wild constraint variables.
The current implementation requires that all types used in a single type parameter are equal. This is probably too restrictive. Let me know if you …

Check arguments to generic functions

---

clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/basic_inter_field.c
clang/test/CheckedCRewriter/basic_inter_field_arr.c
clang/test/CheckedCRewriter/basic_inter_field_ntarr.c
clang/test/CheckedCRewriter/basic_inter_ntarr.c
clang/test/CheckedCRewriter/basic_local_ntarr.c
clang/test/CheckedCRewriter/basic_return_itype.c
clang/test/CheckedCRewriter/no_casts.c

Changed rewriting so that we only insert `void` for nullary functions when their return types are pointer types. 
Closes #182 
Closes #183

Fix for issue 182/183 - The Sequel

---

clang/include/clang/CConv/TypeVariableAnalysis.h
clang/lib/CConv/ConstraintResolver.cpp
clang/test/CheckedCRewriter/stmtExpr.c
clang/test/CheckedCRewriter/stmtExprA.c
clang/test/CheckedCRewriter/stmtExprBUG.c

Closes #190 
This provides a fix for the inference of statement expressions and consistently creates a flow between the outer variable and variables declared within the statement expression.  
Was on branch iss190, but solved merge conflicts with unnecessary visitors. 
Includes support for fixing an initialization issue that caused undefined behavior, courtesy of @jackastner 
Also added one passing test.

Fix for issue 190

---

clang-tools-extra/clangd/tool/ClangdMain.cpp
clang/include/clang/CConv/CCGlobalOptions.h
clang/include/clang/CConv/CConv.h
clang/lib/CConv/ArrayBoundsInferenceConsumer.cpp
clang/lib/CConv/CConv.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/Utils.cpp
clang/test/CheckedCRewriter/user_malloc.c
clang/tools/cconv-standalone/CConvStandalone.cpp

Fix for #220 
Allows the usage of a commandline flag `-use-malloc=<>` in order to treat custom allocator functions the same as malloc (the default is malloc). 
Added a passing test to highlight this issue.
This fix was slightly tricky, but mostly straightforward, so we can also discuss adding a config file for the more general purpose stopgap fix @mwhicks1 suggested in a followup to the issue.

Fix issue 220

---

clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/TypeVariableAnalysis.h
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/TypeVariableAnalysis.cpp
clang/test/CheckedCRewriter/3d-allocation.c
clang/test/CheckedCRewriter/type_params.c

Fixes 2 bugs (#213) in type argument insertion demonstrated by the test case below. In the first function, the type parameter was instantiated to `_Ptr<int>` even though `a` is used unsafely. In the second function, the local variable is rewritten to `_Ptr<int>` even though the type parameter could not be instantiated. 
```c
_Itype_for_any(T) void *test1(void) : itype(_Ptr<T>);
_Itype_for_any(T) void *test2(void * t : itype(_Ptr<T>)) : itype(_Ptr<T>);
void f0() {
int **a = test2();
// CHECK: _Ptr<int *> a =  test2<int *>();
*a = (int*)1;
}
void f1(int **a) {
// CHECK: void f1( int **a) {
int *b = test1(a);
// CHECK: int *b = test1(a);
}
```
A big part of this fix was modifiy constraint generation on function calls so that  the constraint graph for this function
```c
_Itype_for_any(T) void …
```

Type argument insertion bug fix

---

clang/include/clang/CConv/TypeVariableAnalysis.h
clang/lib/CConv/RewriteUtils.cpp
clang/lib/CConv/TypeVariableAnalysis.cpp
clang/test/CheckedCRewriter/type_params.c

This turned out to be a quicker fix than I was expecting it to be.

Check for explicit void type arguments

---

clang/include/clang/CConv/CastPlacement.h
clang/include/clang/CConv/ConstraintsGraph.h
clang/include/clang/CConv/ProgramInfo.h
clang/lib/CConv/CastPlacement.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/itypecast.c

Fix the cast insertion problem brought up in issue #231 where unnecessary casts would be added onto arguments to itype functions in successive invocations of 3C. To fix this, the cast insertion visitor checks if a cast already exists on and expression when inserting a new cast. If there is a cast, the existing cast type is replaced by the new cast type.

Avoid inserting redundant casts on itype arguments on successive invocations 

---

clang/include/clang/CConv/CheckedRegions.h
clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/ProgramInfo.h
clang/include/clang/CConv/Utils.h
clang/lib/CConv/AVarBoundsInfo.cpp
clang/lib/CConv/CastPlacement.cpp
clang/lib/CConv/CheckedRegions.cpp
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/DeclRewriter.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/TypeVariableAnalysis.cpp

Some of the `std::set<ConstraintVariable*>` sets we have are being used exclusively as singleton sets. This pull requests removes these sets, replacing them with a single ConstraintVariable pointer.
The first two commits should not be controversial. These add `const` qualifiers onto method declarations to make it easier to identify where constraint variable sets can possibly be mutated. After adding the `const`s, I only have to look at the non-`const` methods that access a set to determine if the set is used exclusively as a singleton set.
The third commit adds `override` annotations to the `ConstraintVariable` class hierarchy. This helps ensure I haven't broken an virtual methods while adding consts to their signatures. 
The next three commits are the body of this pull requests. Each of …

Refactoring to remove singleton ConstraintVariable sets

---

clang/include/clang/CConv/AVarBoundsInfo.h
clang/include/clang/CConv/CheckedRegions.h
clang/include/clang/CConv/ConstraintResolver.h
clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/Constraints.h
clang/include/clang/CConv/ProgramInfo.h
clang/include/clang/CConv/RewriteUtils.h
clang/include/clang/CConv/Utils.h
clang/lib/CConv/AVarBoundsInfo.cpp
clang/lib/CConv/ArrayBoundsInferenceConsumer.cpp
clang/lib/CConv/CastPlacement.cpp
clang/lib/CConv/CheckedRegions.cpp
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/DeclRewriter.cpp
clang/lib/CConv/PersistentSourceLoc.cpp
clang/lib/CConv/ProgramInfo.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/lib/CConv/StructInit.cpp
clang/test/CheckedCRewriter/definedType.c
clang/test/CheckedCRewriter/macroConcat.c
clang/test/CheckedCRewriter/qualifiers.c

This pull request is a fix for the macro expansion bug in issues #255 and #18 . This bug was caused because by collisions between persistent source locations. Using our current source location representation, it is possible to for two distinct objects to reside at the same source location. The fix I've implemented does not directly address this. Instead it improves the how we handle situations when such a collision is found.
When a source location collision is found, the affected constraint variables are immediately constrained to wild, and a single wild constraint variable is stored in the variables map. Forcing these constraints to be wild is fine because source location collisions occur inside macros, which are always wild anyways. This avoids inconsistent handling of non-singleton …

Fix macro expansion bug

---

clang/include/clang/CConv/AVarBoundsInfo.h
clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/PersistentSourceLoc.h
clang/include/clang/CConv/ProgramVar.h
clang/include/clang/CConv/RewriteUtils.h
clang/lib/CConv/AVarBoundsInfo.cpp
clang/lib/CConv/ArrayBoundsInferenceConsumer.cpp
clang/lib/CConv/ConstraintBuilder.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/DeclRewriter.cpp
clang/lib/CConv/PersistentSourceLoc.cpp
clang/lib/CConv/ProgramVar.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/3d-allocation.c
clang/test/CheckedCRewriter/contextsensitivebounds1.c

We will create context-sensitive bounds key for inferring array bounds. Previously, we did this only for functions that have bounds declarations, but this pull-request extends this to all functions.
Consider the following code:
```
struct hash_node
{
int *w_key;
int *y_key;
unsigned xo;
unsigned lo;
};
void ctxsensfunc(int *p, unsigned n) {
unsigned i;
for (i=0; i<n; i++) {
p[i] = 0;
}
}
int foo() {
unsigned j;
struct hash_node *n
ctxsensfunc(n->w_key, n->xo);
j = n->lo;
ctxsensfunc(n->y_key, j);
return 0;
}
```
Here, for each of the call-sites of `ctxsensfunc` we create new BoundsKey and array length inference will correctly infer the length of the structure members as follows:
```
struct hash_node
{
_Array_len<int> w_key : count(xo);
_Array_len<int> y_key : count(lo);
unsigned xo; …
```

Context sensitive array bounds for all function calls

---

clang/include/clang/CConv/ConstraintVariables.h
clang/lib/CConv/AVarBoundsInfo.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/RewriteUtils.cpp
clang/test/CheckedCRewriter/basic_checks.c
clang/test/CheckedCRewriter/simple_locals.c

Now, we correctly generate bounds and also there are a couple of test cases where we find bounds.

Fixing issue https://github.com/plum-umd/checkedc-clang/issues/276

---

clang/include/clang/CConv/ProgramVar.h
clang/lib/CConv/AVarBoundsInfo.cpp
clang/lib/CConv/ProgramVar.cpp

Fixing use-after-free in array bounds inference: https://github.com/correctcomputation/checkedc-clang/runs/1164888459?check_suite_focus=true

Fixing user-after-free in ProgramVar

---

clang/include/clang/CConv/ConstraintVariables.h
clang/include/clang/CConv/DeclRewriter.h
clang/include/clang/CConv/RewriteUtils.h
clang/lib/CConv/ConstraintResolver.cpp
clang/lib/CConv/ConstraintVariables.cpp
clang/lib/CConv/DeclRewriter.cpp
clang/lib/CConv/RewriteUtils.cpp

Three miscellaneous changes made while working on the root cause of wildness analysis.
1. Calls to allocater functions will now generate a single atom. Previously, two atoms were generated to act as the parameter and argument atoms for the function, even though these function are handled differently than other function, and don't need the separate parameter atom.
2. The function `ConstraintVariable::constrainToWild` now only adds a constraint on the outer pointer level. The inner pointer levels are implicitly constrained by implication constraints.
3.  A bug is fixed in multi-declaration rewriting that was caused by undefined ordering of a set of `Decl*`.

Refactoring and bug fix changes

---

clang-tools-extra/clangd/tool/CMakeLists.txt
clang/tools/3c/utils/port_tools/generate_ccommands.py

For testing, in order to get a configuration with any of the clangd targets present, you have to pass `'-DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra' -DCLANG_ENABLE_CLANGD=ON` on the cmake command line.  You may have to delete everything in the `build` directory before this will work.
I confirmed with `ninja -n` that before this change, `clangd` and `clangd3c` both exist, while after it, `clangd` exists and `clangd3c` does not.
Note that before this change, `clangd3c` fails to build.  While #299 introduced some additional breakages due to collisions between field and type names (something I'd ideally have been more careful about), I confirmed that the old `icconv` target was broken at least as far back as 3892e314426e8d90b4d3d411e1aaaf636dac47ea, apparently due to some occurrences of …

Disable clangd3c build target, which is unmaintained and broken.

---

clang-tools-extra/clangd/CMakeLists.txt
clang-tools-extra/clangd/tool/CMakeLists.txt
clang/lib/3C/CMakeLists.txt
clang/tools/3c/CMakeLists.txt

This neatly resolves the confusing near-collision between the executable
target (renamed from cconv-standalone to 3c in #299) and the library
target (renamed from CConv to 3C).
`ninja check-clang-3c` passes (after deleting everything in the `build` directory: sigh).

Rename the clang/lib/3C target to clang3C, following convention.

---

clang-tools-extra/clangd/3CCommands.cpp
clang-tools-extra/clangd/3CCommands.h
clang-tools-extra/clangd/ClangdLSPServer.cpp
clang-tools-extra/clangd/ClangdServer.cpp

Specifically, AsCCCommands and ExecuteCCCommand.  These are used only in
clangd3c, which we're about to disable, but the intent of #299 was to
process the whole source tree.  These do not appear in the currently
existing 5C-specific code.
This change intentionally does not address:
- Local variables (except one as requested by Mike).  They aren't
important and their naming varies too much to make it easy to find all
of them.
- Name collisions between fields or local variables and their types.  In
my tests so far, a field collision causes a compile error, while a
local variable collision doesn't.  I saw the clangd3c build fail due
to field collisions (we know there are none in 3c because it builds),
and this led me to discover some local variable collisions in both
clangd3c and 3c.  But we …

Rename two identifiers missed in #299.

---

clang/tools/3c/utils/update-includes.py

I'm not sure under what conditions the existing default (apparently based on the working directory) was supposed to work.  This should work all the time if the Checked C system headers have been installed according to our upcoming instructions.  I have tested it with `checkedc-tiny-bignum-c`.
Bonus: Make update-includes.py directly executable.

update-includes.py: Find the default header location relative to update-includes.py itself.

---

clang/test/3C/find_bin.py
clang/test/3C/processor.py
clang/test/3C/test_updater.py
clang/test/3C/testgenerator.py

This is to facilitate my work on factoring the `RUN` commands out of the test files for #346.

Minor improvements to test updating programs

---

clang/include/clang/3C/3C.h
clang/lib/3C/3C.cpp
clang/test/3C/partial_checked_arr.c
clang/test/3C/root_cause.c
clang/tools/3c/3CStandalone.cpp

This means we now verify the line numbers of the diagnostics for free, which would have been a pain with the existing CHECK-DAG system.
- Make the 3c tool accept a -verify option analogous to that of `clang -cc1` to verify diagnostics against `// expected-warning` comments. Currently, this applies only to the rewriting phase.
- Fix a few mistakes in the expected diagnostics in the root_cause test.
**Issues for special attention in code review:**

Convert root_cause test to use Clang's built-in diagnostic verifier.

---

clang/lib/3C/ConstraintVariables.cpp
clang/test/3C/compound_literal.c

This test started failing due to issue microsoft#870 which was later fixed by PR microsoft#899. That pull request is now merged into our fork, so this test should be passing again. Another bug slipped into this test in PR #242 that caused constant array sizes to be dropped in compound literal expressions. This has also been fixed.

Enable test compound_literal.c

---

clang/include/clang/3C/DeclRewriter.h
clang/lib/3C/ConstraintBuilder.cpp
clang/lib/3C/DeclRewriter.cpp
clang/test/3C/alloc_type_param.c
clang/test/3C/inline_anon_structs.c

This PR does several things: 
1. only marks inline (anonymous) structs wild when alltypes is disabled. 
2. instead issues a warning when alltypes is enabled 
3. splits named inline structs to two separate decls (works for both globally declared VarDecls and those declared within functions) 
Lessons learned: inline structs with global scope are treated as single decls (namely, the VarDecl), however inline structs within functions are treated as multi-decls (including both the RecordDecl *and* the VarDecl). This was a source of major blockage for me when debugging, so I'm putting this information here for now, but will document it officially tomorrow. (In fact, I think this might have something to do with why statement expressions #195 are also rewritten poorly, though its hard to tell). …

Inline struct rewriting support

---

clang/include/clang/3C/ConstraintVariables.h
clang/include/clang/3C/TypeVariableAnalysis.h
clang/include/clang/3C/Utils.h
clang/lib/3C/CastPlacement.cpp
clang/lib/3C/ConstraintBuilder.cpp
clang/lib/3C/ConstraintResolver.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/ProgramInfo.cpp
clang/lib/3C/TypeVariableAnalysis.cpp
clang/lib/3C/Utils.cpp

Change the generic flag to an index, and have other functions rely on this index rather than regenerating it from decl itypes. This is in preparation for changing these indexes in TypeVariableAnalysis later, so that we can i.e. change `void *` to `T *`.
All other functionality remains unchanged. Regression tests are unaffected.

Refactor to include generic types info in VCs

---

clang/tools/3c/CMakeLists.txt

[Discussed here](https://correct-computation.slack.com/archives/G01GKGKHMFD/p1610556664015500?thread_ts=1610553768.008000&cid=G01GKGKHMFD).  `ninja check-clang-3c` passes (I couldn't foresee any way this change could break it).

Make 3c depend on the system headers (original and Checked C).

---

clang/lib/3C/DeclRewriter.cpp

Nulls out the static field LastRecordDecl, publishing as a PR to get the go-ahead that this fix actually addresses the vsftpd vulnerability.

Fixing inline struct rewriting bug on vsftpd

---

clang/lib/3C/ConstraintVariables.cpp

Disable checks that were used to verify that the relationships between constant atom were valid. While we do not generally intend to rewrite code in a way that violates these relationships, it is possible for a user of 3C to manually modify their code so that it does while still having valid CheckedC code.

Disable assertions checking for constraint validity

---

clang/include/clang/3C/3C.h
clang/include/clang/3C/3CGlobalOptions.h
clang/lib/3C/3C.cpp
clang/lib/3C/RewriteUtils.cpp
clang/tools/3c/3CStandalone.cpp

I hope this change is simple enough and decoupled enough from our other work that it doesn't need a regression test. I tested it once manually.

Add a flag to downgrade the "unwritable change" error to a warning.

---

clang/include/clang/3C/RewriteUtils.h
clang/include/clang/3C/Utils.h
clang/lib/3C/DeclRewriter.cpp
clang/lib/3C/Utils.cpp
clang/test/3C/functionDeclEnd.c

Fixes #392. A right parentheses appearing between a function prototype and the
beginning of its definition caused anything falling between the
parenthesis and the actual end of the prototype to be deleted. This
problem is fixed by using clang provided source locations instead of
locating the closing parenthesis by iterating of the source code
characters.

Fix function rewriting with r-paren between prototype and definition

---

clang/include/clang/3C/ProgramInfo.h
clang/lib/3C/ProgramInfo.cpp
clang/test/3C/defn_then_decl.c

Ensure that constrains generated due to a function's declaration are
applied to the variables generated at the definition even when
declaration appears after the definition. This is done by copying
the atoms from the definition constraint variable into the declaration
constraint variable using `brainTransplant` before any constraints are
added on the declaration.

Handle function declaration appearing after definition (fix #399)

---

clang-tools-extra/clangd/ClangdServer.cpp
clang/lib/3C/ArrayBoundsInferenceConsumer.cpp

Fix for: https://github.com/correctcomputation/checkedc-clang/issues/415
There is a chance of clang CFG not having appropriate basicblock, we check to see if we have the basicblock else ignore the heuristic.
I also fixed a minor issue with `clangd`, which has a compilation problem as the `solveConstraints` interface changed.

Fixing Issue 415

---

clang/lib/3C/CheckedRegions.cpp
clang/test/3C/base_subdir/canwrite_constraints.c
clang/test/3C/graphs.c
clang/test/3C/subtyp.c
clang/test/3C/supernested.c

I noticed this apparent bug while trying to write a regression test for #423.  Is this seemingly obvious fix correct, or should I file an issue for further discussion?  Do we need a dedicated regression test, or can we rely on the existing tests that expected the buggy behavior and that I'm updating to expect the corrected behavior?
Aaron: I'm tentatively requesting review from you since I see you've done some work on checked regions.  If you're not familiar enough with the topic to be confident about this change, we can ask John.

CheckedRegionFinder: "void" does not contain an unchecked pointer.

---

clang/lib/3C/ConstraintVariables.cpp

The liberal itypes change (#356) added code to flag them as not having a
body even though they did. This may have been a useful mitigation for
certain problems with unwritable files at the time, but it risks causing
confusion and violating 3C invariants in the future. From now on, we
want to handle all unwritable files (including system headers) via the
new canWrite constraints approach.
It appears that removing this code will immediately fix one problem with
cast insertion that is currently blocking the benchmark tests (#423), so
we'll go ahead and make this change even though we don't fully
understand the cast insertion problem or how to appropriately
regression-test it.

Remove special handling of functions defined in system headers.

---

clang/test/3C/bodiless.c

Hopefully fixes #378 for real this time.
I tested via a temporary `chmod u-w clang/test/3C` on my laptop that no other tests try to create files in the directory.  I assume that result will hold true on Windows too.

bodiless.c: Don't write a temporary file in the source directory.

---

clang/test/3C/allocator.c
clang/test/3C/liberal_itypes_ptr.c

The one in liberal_itypes_ptr.c conflicted with the system headers on
Windows X64. We haven't seen a problem with the one in allocator.c yet,
but let's remove it too for consistency.
Fixes #451.

3C regression tests: Replace remaining size_t typedefs with stddef.h.

---

clang/lib/3C/ConstraintVariables.cpp

Even though references don't exist in C, `va_list` is a typedef of
`__builtin_va_list &` on windows. In order to generate correct constraints
for var arg functions on windows, we need to strip the reference type.

Fix failing test valist.c for windows

---

clang/test/3C/CMakeLists.txt
clang/test/CMakeLists.txt

This may significantly speed up the build.
(As I've mentioned elsewhere, I believe many of the removed steps are link steps that are especially slow on Windows.  Indeed, my recent Windows builds of `check-3c` have been much faster than my previous builds of `check-clang-3c`.  However, I haven't taken the time to perform a direct comparison to rule out other explanations for the difference, so I'm not making a more definite statement about the build time in the files.)
I'll make the corresponding documentation update in this repository separately, presumably as part of #438.

Add `check-3c` target with fewer dependencies than `check-clang-3c`.

---

clang/lib/3C/CastPlacement.cpp
clang/test/3C/canwrite_constraints.h

See #454.
Unblocks the Windows tests from #449 (and may unblock #446 from #423: not tested).

Skip cast insertion in unwritable files with a warning.

---

clang/lib/3C/DeclRewriter.cpp
clang/test/3C/ms_extensions.c

Avoids a crash when an implicit `struct _GUID` is injected with an
invalid source location on Windows (fixes #448).

DeclRewriter::detectInlineStruct: Skip structs with invalid source locations.

---

clang/lib/3C/ConstraintResolver.cpp
clang/test/3C/definedType.c
clang/test/3C/malloc_implicit_cast.c

This was the cause of the `definedType.c` failure on Windows X86, so we
can now re-enable that test. We also have a dedicated test for the bug
that should work in our main Linux environment.
Fixes #345.

Fix detection of `malloc(a * sizeof(b))` with implicit casts.

---

clang/lib/3C/ConstraintBuilder.cpp
clang/test/3C/struct_macro.c

This fixes #297 which is blocking libarchive. It's a simple fix, but I'm a little hesitant  to remove the `if (FE && FE->isValid())` conditional without understanding why it was there in the first place.

Remove conditional stopping creating of constraint variables

---

clang/lib/3C/CastPlacement.cpp

The `if` statement that tries to replace an existing cast with a new cast
assumed that the new cast was a c-style cast and not a CheckedC
bounds cast. If the branch was taken when inserting a bounds cast,
the leading '_' was cut off, resulting in invalid code. This commit
adds a condition that ensures this does not happen.
I added an assert for this invariant in one of the PRs I merged earlier
today, but somehow didn't see the obvious way that it can be violated.

Fix placement of _Assume_bounds_cast on c-style cast

---

clang/include/clang/3C/3C.h
clang/include/clang/3C/3CGlobalOptions.h
clang/lib/3C/3C.cpp
clang/lib/3C/RewriteUtils.cpp
clang/test/3C/base_subdir/canwrite_constraints_symlink.c
clang/test/3C/base_subdir/canwrite_constraints_unimplemented.c
clang/test/3C/macro_rewrite_error.c
clang/test/3C/stdout_mode_write_other.c
clang/tools/3c/3CStandalone.cpp

While we're here:
- Add note about -allow-unwritable-changes to the unwritable change
error, and change the existing note to have no location for
consistency with the others.
- Fix a highly visible typo in a `3c` error message.
Our practice so far has been not to add regression tests specifically for the `-allow-*` flags.  I believe I tested all the combinations manually, in addition to running `ninja check-3c`.

Add -allow-rewrite-failures option to downgrade rewrite errors to warnings.

---

clang/lib/3C/ProgramInfo.cpp
clang/test/3C/canwrite_constraints.h

This should fix the failure in the vsftpd benchmark with #463.

Constrain expression variables in unwritable files to not change.

---

clang/include/clang/3C/ConstraintVariables.h
clang/lib/3C/ConstraintBuilder.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/test/3C/merge_fp1_xfail.c
clang/test/3C/merge_fp2.c

Remove now-vestigial code after brainTransplant was removed. Also, include tests of known failure merging function pointers.

Remove defered params

---

clang/include/clang/3C/3C.h
clang/test/3C/stderr_clean.c

They were already also printed to TotalConstraintStats.json when -dump-stats is passed.
Also add a regression test that 3C's stderr is empty by default on a successful run.
Fixes #478.

Don't print the performance statistics unconditionally.

---

clang/include/clang/3C/RewriteUtils.h
clang/include/clang/3C/TypeVariableAnalysis.h
clang/lib/3C/CheckedRegions.cpp
clang/lib/3C/ProgramInfo.cpp
clang/lib/3C/RewriteUtils.cpp
clang/lib/3C/TypeVariableAnalysis.cpp
clang/test/3C/type_params_macro.c

Fixes #315.
Calls to polymorphic functions in macros no longer fail an assert.
These calls also no longer trigger a checked region.
If calls come from a macro they are marked inconsistent, and this is available through ProgramInfo globals.

Calls to polymorphic functions in macros no longer fail an assert

---

clang/tools/3c/utils/port_tools/generate_ccommands.py

We've found it more distracting than helpful.
Example workflow runs:
- [Before](https://github.com/correctcomputation/actions/runs/2119440717?check_suite_focus=true): The conversion log is full of `-dump-intermediate` output and is truncated.
- [After](https://github.com/correctcomputation/actions/runs/2123670207?check_suite_focus=true): The symbolized stack trace of the assertion failure is visible at the end of the conversion log.

convert_project: Turn off -dump-intermediate by default.

---

clang/test/3C/diag_verifier_fail.c
clang/test/3C/diag_verifier_pass.c
clang/test/3C/stdout_mode_write_other.c

I noticed some problems when I manually tested of the current draft of #488 and realized we didn't have regression tests for them.  This PR rectifies that.

Add regression tests for diagnostic processing.

---

clang/lib/3C/ConstraintResolver.cpp
clang/test/3C/valist.c

Use of VarArg parameters are assumed to be unsafe even though CheckedC will
accept them with checked pointer types. If we want to support VarArgs with
checked pointer types, we can remove the constraint to WILD here. We would then
need to update TypeExprRewriter to rewrite the type in these expression.

Make accessing va_list parameters unchecked (fix #483)

---

clang/include/clang/3C/DeclRewriter.h
clang/include/clang/3C/RewriteUtils.h
clang/include/clang/3C/Utils.h
clang/lib/3C/DeclRewriter.cpp
clang/lib/3C/RewriteUtils.cpp
clang/lib/3C/Utils.cpp
clang/test/3C/k_and_r.c

For example
```c
void f(x)
int *x;
{ }
```
can now rewrite to 
```c
void f(_Ptr<x>)
{ }
```
fixes issue #93

Fix rewriting for K&R style function

---

clang/include/clang/3C/StructInit.h
clang/include/clang/3C/Utils.h
clang/lib/3C/StructInit.cpp
clang/lib/3C/Utils.cpp
clang/test/3C/add_struct_init.c

Updates `StructVariableInitializer::variableNeedsInitializer` to check if any field of a structure need an initializer. This detects if any nested structure has a checked pointer as a field.

Add initializer when nested structure has checked field (fix #495)

---

clang/include/clang/3C/ConstraintVariables.h
clang/include/clang/3C/DeclRewriter.h
clang/lib/3C/CastPlacement.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/DeclRewriter.cpp
clang/lib/3C/RewriteUtils.cpp
clang/test/3C/liberal_itypes_fp.c

The code for deciding if a function should get an itype was duplicated
for functions declarations and function pointer types. The function
pointer version of the code had a bug in it that caused issue #498.
The duplicated code has been extracted into single function that is
reused for functions and function pointers.
A lot of the lines changed in this PR are caused by an `EnvironmentMap&`
parameter being changed to `Constraints&`. This lets the function pointer
code call `solutionEqualTo` which is needed for correct itype insertion.

Fix condition for adding itypes in function pointers

---

clang/include/clang/3C/Utils.h
clang/lib/3C/PersistentSourceLoc.cpp
clang/lib/3C/RewriteUtils.cpp
clang/lib/3C/Utils.cpp

Pulled out of https://github.com/correctcomputation/checkedc-clang/pull/488#discussion_r599546827 to ease review.
I'd prefer to have at least the two big comments near the `tryGetRealPathName` calls added to #488 to document the changes made there.  If you don't want to deal with the diagnostic code changes and the related cleanup at this time, that's completely fine with me; let me know and I'll remove them from this PR.

Slight improvements and comments for file path canonicalization (for possible addition to #488)

---

clang/lib/3C/3C.cpp
clang/test/3C/macro_function_call.c

PR #488 made `3c -verify` cover only the compiler diagnostics, but none of our regression tests actually use that functionality. Instead, one regression test (macro_function_call) used `3c -verify` to try to test the absence of 3C warnings, and we were unaware that the test wasn't testing what it was supposed to. I think it's best to make `3c -verify` an error for now so we don't make that mistake again.

Make `3c -verify` an error for now.

---

clang/include/clang/3C/AVarBoundsInfo.h
clang/lib/3C/AVarBoundsInfo.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/test/3C/arrboundsprototypemerge.c
clang/test/3C/ptrtoconstarr.c

The new logic to merge multiple prototypes of functions was not handled correctly in the bounds inference code.
Added code to handle the merging of bounds key.

Fix bounds inference breakage due to declaration merging change (issue #522)

---

clang/lib/3C/3C.cpp
clang/tools/3c/utils/port_tools/generate_ccommands.py

Fixes #529.
This just needs a regression test.  I'd have to figure out the best way to create a compilation database as part of the regression test _and_ demonstrate a problem even if, in the future, we change 3C to always use the presumed file path rather than overriding it with the `SM.getFileEntryForID(TFSL.getFileID())` in some cases (which is what triggered #529).

Ensure presumed source file paths are canonical when using a compilation database.

---

clang/lib/3C/DeclRewriter.cpp
clang/test/3C/add_bounds.c

This change lets 3C add inferred bounds onto checked array pointer even when the type of the pointer has not otherwise changed. Fixes #538 
---
[benchmarks](https://github.com/correctcomputation/actions/actions/runs/733775948)

Add new array bounds even when pointer type does not change

---

clang/include/clang/3C/CastPlacement.h
clang/lib/3C/CastPlacement.cpp
clang/test/3C/itype_nt_arr_cast.c

Fixes #545.
e.g.,
```c
char *fn2(void) : itype(_Nt_array_ptr<char>);
char *caller2() {
// _Nt_array_ptr<char> caller2(void) {
char *a = fn2();
// _Nt_array_ptr<char> a = ((_Nt_array_ptr<char> )fn2());
return a;
}
```
---
[benchmarks](https://github.com/correctcomputation/actions/actions/runs/743081887)

Add cast for `itype(nt_array_ptr)` to `nt_array_ptr` assignment

---

clang/include/clang/3C/Utils.h
clang/lib/3C/ConstraintBuilder.cpp
clang/lib/3C/Utils.cpp
clang/test/3C/printf_ntarr.c

Constrain `printf("%s")` arguments to `_Nt_array_ptr`.

---

clang/lib/3C/TypeVariableAnalysis.cpp
clang/test/3C/func_name_parens.c

Don't crash on a function call with parentheses around the function name.

---

clang/test/3C/issue523.c

I checked that, as of now, this test still crashes 3C if 09544a0e3e7151787e6c08529f494e48caf412ce is reverted.

Add regression test for #523.

---

clang/test/3C/basic.c
clang/test/3C/graphs.c

This is the minimum to fix the regression tests broken by our changes to system headers so far (#560) so we can more easily continue to test other changes to 3C. We plan to continue making changes to the system headers that may cause similar problems, so we want to finish cleaning up the rest of the regression tests ASAP.

Remove old realloc, etc. declarations from basic.c and graphs.c.

---

clang/lib/3C/RewriteUtils.cpp
clang/test/3C/type_param_psl_collision.c

Fix one crash due to a PSL collision in TypeParamBindings.

---

clang/include/clang/3C/ConstraintVariables.h
clang/lib/3C/ConstraintVariables.cpp
clang/test/3C/basic.c
clang/test/3C/graphs.c
clang/test/3C/keep_array_size_expr.c
clang/test/3C/macro_end_of_decl.c
clang/test/3C/multivardecls.c
clang/test/3C/patch_issue_272.c

Keeps track of the original source representation for the size of constant sized arrays and use this when rewriting to a checked array types. This also handles various other constant expression in the size of an array.
```c
int a[1];
int b[1 + 1];
int c[1 /*test*/];
#define FOO 10
int d[FOO];
int e[FOO + FOO];
int f[sizeof(int)];
```
now converts to
```c
int a _Checked[1];
int b _Checked[1 + 1];
int c _Checked[1 /*test*/];
#define FOO 10
int d _Checked[FOO];
int e _Checked[FOO + FOO];
```
fixes #173

Avoid expanding macros in array declarations

---

clang/lib/3C/ConstraintVariables.cpp

Fixes #584 by properly initializing the typedef info structure in the copy constructor for `PointerVariableConstraint`.

Initialize typedef info structure

---

clang/lib/3C/ConstraintVariables.cpp

An unused code path would have resulted in a infinite loop if anything
ever tried to execute it.

Fix bug in PVConstraint copy constructor

---

clang/test/3C/statstest.c

- It made an invalid assumption that stdout was flushed before stderr, which failed on Windows. To avoid that, check stdout and stderr separately.
- That fix revealed that the CHECK comments weren't correct, but they were passing because they were matching themselves (!) because -match-full-lines was removed in #566. Fix the syntax for regular expressions (double curly braces, not single) and the incorrect expected values for two statistics.

Fix statstest.

---

clang/test/3C/addrof_crash.c
clang/test/3C/allocator.c
clang/test/3C/basic_checks.c
clang/test/3C/basic_inter_field.c
clang/test/3C/basic_inter_field_arr.c
clang/test/3C/basic_local_field.c
clang/test/3C/boundary_tests.c
clang/test/3C/bounds_interface.c
clang/test/3C/cant_be_nt.c
clang/test/3C/const_tests.c
clang/test/3C/global.c
clang/test/3C/multipledecls.c
clang/test/3C/placements.c
clang/test/3C/ptrtoconstarr.c
clang/test/3C/simple_locals.c
clang/test/3C/some_checked.c
clang/test/3C/struct_init_list.c
clang/test/3C/typedefbounds.c
clang/test/3C/typedefnoptr.c
clang/test/3C/typedefs.c
clang/test/3C/vargs.c

This requires replacing `%clang_cc1 -verify` with `%clang -Xclang -verify` in the tests that use it.
This is one part of the RUN command cleanup that we've wanted to do for a while in #346, and now it is blocking part of #576. This is because the single behavior difference we know of between %clang_cc1 and %clang (other than the need for `-Xclang`) is that %clang_cc1 turns off the system headers, and we want two of our tests that currently use %clang_cc1 to be able to get checked declarations from the system headers.
As recently as dac3f9775eb966bd83055bfff2ef07de28a610a3 (August 2020), all of the tests that used %clang_cc1 used -verify. Since then, a few tests have been added that use %clang_cc1 and not -verify. This lends support to my theory that the only reason we used %clang_cc1 was …

Migrate 3C regression tests from %clang_cc1 to %clang.

---

clang/include/clang/3C/ConstraintVariables.h
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/ProgramInfo.cpp
clang/test/3C/base_subdir/canwrite_constraints.c
clang/test/3C/base_subdir/canwrite_constraints_unimplemented.c
clang/test/3C/canwrite_constraints.h

Fixes #581.
I'm aware of one potential behavior change in this PR: a generic `FVComponentVariable` will cause a `ReasonUnchangeable` to be set on the recursive `equateWithItype` call where the equivalent `ForceEquate` previously wasn't set, which IIUC could affect the handling of function pointers.  But this case isn't covered by our regression tests, and IMO it would be a bit unfair to expect me to investigate the behavior and test it one way or another as part of this PR.  Furthermore, I suspect there may be another bug with function pointers anyway: if a function parameter doesn't itself have an itype but some function pointer inside it has parameters that do, I imagine we want to process those itypes, but currently `equateWithItype` doesn't traverse them at all.  If we really want, I …

Fix `canwrite_constraints` test and constrain itypes in unwritable files.

---

clang/lib/3C/TypeVariableAnalysis.cpp
clang/test/3C/canwrite_constraints.h

Don't allow type arguments to be added to generic function calls in unwritable files.

---

clang/tools/3c/utils/port_tools/convert_project.py

Super small fix to have `convert_project.py` correctly give a non-zero exit code when it errors.

convert_project.py now exits w/ non-zero on error

---

clang/include/clang/3C/ABounds.h
clang/include/clang/3C/AVarBoundsInfo.h
clang/lib/3C/ABounds.cpp
clang/lib/3C/AVarBoundsInfo.cpp
clang/lib/3C/ArrayBoundsInferenceConsumer.cpp
clang/test/3C/allarrays.c
clang/test/3C/arrboundsheuristics.c
clang/test/3C/arrctxsenbounds.c
clang/test/3C/lowerbound.c
clang/test/3C/malloc_array.c
clang/test/3C/multidef1a.c
clang/test/3C/multidef1b.c
clang/test/3C/placements.c
clang/test/3C/realloc.c
clang/test/3C/realloc_complex.c
clang/test/3C/refarrsubscript.c
clang/test/3C/resolve_itypes.c
clang/test/3C/simple_locals.c
clang/test/3C/untypedprototypes.c

This will add a new heuristic, where the bounds of an array will be inferred as index + 1.
For instance, for the following code:
```
int getX(int *x) { return x[0]; }
int getY(int *x, int i) { return x[i]; }
```
The bounds will be inferred as follows:
```
int getX(_Array_ptr<int> x : count(0 + 1)) { return x[0]; }
int getY(_Array_ptr<int> x : count(i + 1), int i) { return x[i]; }
```
More details: https://github.com/correctcomputation/checkedc-clang/issues/599
This improves the bounds inference of other benchmarks as well.
For `yacr2` of `ptrdist`:
```
ulong ExistPathAboveVCG(_Array_ptr<nodeVCGType> VCG : count(below + 1), ulong above, ulong below)
{
DFSClearVCG(VCG);
DFSAboveVCG(VCG, above);
return(VCG[below].netsAboveReached);
}
```
That further added bounds to other functions:
``` …
```

Adding bounds inference of the form count(i+1)

---

clang/include/clang/3C/ConstraintVariables.h
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/ProgramInfo.cpp
clang/test/3C/base_subdir/canwrite_constraints.c
clang/test/3C/canwrite_constraints.h
clang/test/3C/root_cause.c

Fixes #609.
I copied part but not all of #578 (namely, the fix to only count atoms in writable code) into this PR because I needed it to get the existing tests to pass; without it, I got loads of warnings about elements in system headers that the writable code wasn't even using.  I haven't looked into what introduced this problem between when the root cause tests were originally disabled and now.
That fix, plus the changes to `equateWithItype` to reach parity with the way PSLs and reasons were previously recorded by `constrainToWild`, seem to be enough to fix the existing tests.  In general, calling `equateWithItype` and `constrainToWild` on the same `ConstraintVariable` and having these interactions in terms of which one shows up as the root cause seems like an awkward design, but I'm …

Fix the root-cause tests.

---

clang/include/clang/3C/PersistentSourceLoc.h
clang/lib/3C/3CInteractiveData.cpp
clang/lib/3C/ProgramInfo.cpp
clang/test/3C/json_formatting.c
clang/test/3C/json_formatting_backslash.c

Other escaping bugs may remain; #620 is to fix all of them.
Fixes #619.
This PR depends on #624 since it adds a second test of the JSON files and if we let both tests write JSON files directly in `build/tools/clang/test/3C`, the tests could interfere if they are run in parallel.  I've set the target branch for review purposes; I'll change it to `main` after #624 is merged.

Fix escaping bugs that currently affect the JSON formatting test on Windows.

---

clang/test/3C/tree.c
clang/test/3C/type_params.c

Add `-D_FORITFY_SOURCE=0` to certain tests as a workaround to issues with Fortify and other compiler builtins. 
(For a long term solution, see: #630 )

Fortify source workaround

---

clang/include/clang/3C/ConstraintResolver.h
clang/lib/3C/ConstraintResolver.cpp
clang/test/3C/simd1.c
clang/test/3C/simd2.c
clang/test/3C/simd3.c

Previously 3c would crash if it found any use of intrinsic types: (ex: `int __attribute__ ((vector_size(16))) x`) 
Now, 3c correctly identifies these as base type. 
Since intrinsic vectors cannot contain pointers, we do not need to generate constraints around them. 
(ie: `int* __attribute__ ((vector_size(16)))` is an invalid type). 
As far as rewriting, if the instrinsics are behind a typedef, then rewriting works fine. However if they are used as raw types rewriting will fail as currently rewriting drops attributes. This is potentially addressed in #466. 
This fixes issues: #632, #381, and #284

3c no longer crashes when encountering intrinsics 

---

clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/ProgramInfo.cpp
clang/test/3C/root_cause.c

Fixes issue where pointers in unwritable code were counted in the root cause analysis. Also fixes an error in `specialCaseVarIntros` where a `void` pointer was sometimes reported as an varargs parameter.

Root cause fixes

---

clang/include/clang/3C/ProgramInfo.h
clang/include/clang/3C/RewriteUtils.h
clang/lib/3C/RewriteUtils.cpp
clang/test/3C/multiple_tu.c

It looks like this change missed #666, so I'm submitting it as a separate PR.

Don't print the main file to stdout multiple times in different translation units.

---

clang/test/3C/functionDeclEnd.c

Fixes #682.
The purpose of this function was to test function declaration rewriting
for itype array pointers declared with bounds but without an explicit
itype. This is equally well tested when a correct bound is inferred for
the parameter array.
This could probably be done a few other ways. What's important though
is that there is still a bound on the return without an itype expression,
and that that the function declaration is rewritten with and without `-alltypes`.

Change test7 in functionDeclEnd.c to infer a valid bound

---

clang/include/clang/3C/AVarBoundsInfo.h
clang/include/clang/3C/ConstraintVariables.h
clang/lib/3C/3C.cpp
clang/lib/3C/AVarBoundsInfo.cpp
clang/lib/3C/ConstraintResolver.cpp
clang/lib/3C/ConstraintVariables.cpp
clang/lib/3C/Utils.cpp
clang/test/3C/canonical_type_cast.c
clang/test/3C/cant_be_nt.c
clang/test/3C/nt_const_arr.c

The Checked C bounds for constant sized `_Nt_checked` arrays is one less
than the written size because the written size counts the null
terminator while the Checked C bounds do not.
To make this change, the declared bounds of constant size arrays must be
added to the array bounds inference information after pointer type
constraint solving. This lets `_Checked` and `_Nt_checked` array be treated
differently.
This also fixes an error in `canBeNtArray` that caused  `ensureNtCorrect `to add
incorrect constraints. The function checked if a type was a `PointerType` or
`ArrayType`, but it could be a wrapper type around one of these types. For
example, `ParenType` and `DecayedType` instances were both treated as
not pointers or arrays even if the type they wrapped was a pointer or array type. …

Treat the bounds of _Nt_checked as one less than the written length

---

clang/lib/3C/ArrayBoundsInferenceConsumer.cpp
clang/test/3C/arrboundsheuristicsitype.c

When adding array bound heuristics, the internal constraint variable for function parameters was used to check the solved pointer type. This made itype parameters look like wild pointers instead of array or nt array pointers.
This resolves the remaining issue in #487

Fix issue causing array bounds heuristics to not apply to itypes

---

clang/include/clang/3C/ConstraintVariables.h
clang/lib/3C/ConstraintVariables.cpp
clang/test/3C/compound_literal.c
clang/test/3C/definedType.c
clang/test/3C/fptr_array.c
clang/test/3C/itype_typedef.c
clang/test/3C/itypes_for_extern.c
clang/test/3C/ptr_array.c

Most of these fixes are ones that were previously needed in #657 when it switched all unchanged multi-decl members from `Decl::print` to `mkString`, in order to prevent 3C's output from getting worse on some unchanged multi-decl members in the regression tests. The fixes are no longer needed for that reason, but Mike still asked me to submit them. See the commit messages for additional information.
This PR addresses several of the sub-issues of #703.

mkString fixes (mostly moved from the multi-decl overhaul)
